#! /bin/sh

set -e

# Generate list of files in debian/ to distribute.
if [ -d .git ]; then
  (echo '# Automatically generated by boot.sh (from Git tree).' &&
   printf 'EXTRA_DIST += \\\n' &&
   git ls-files debian | grep -v '^debian/\.gitignore$' |
   sed -e 's/\(.*\)/    \1 \\/' -e '$s/ \\//') > debian/automake.mk
else
  (echo '# Automatically generated by boot.sh (from ls).' &&
   printf 'EXTRA_DIST += \\\n' &&
   ls debian | grep -v '^debian/\.gitignore$' |
   sed -e 's/^/debian\//' -e 's/\(.*\)/    \1 \\/' -e '$s/ \\//') > debian/automake.mk   
fi

cat debian/control.in > debian/control
# Bootstrap configure system from .ac/.am files
autoreconf --install --force
